#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="x86_64-linux"
FLAKE_SYSTEM="nixosConfigurations.vm.${SYSTEM_TYPE}.config.system.build.vm"

export NIXPKGS_ALLOW_UNFREE=1

echo "${GREEN}Starting virtual machine...${NC}"
nix --extra-experimental-features 'nix-command flakes' run .#$FLAKE_SYSTEM $@
