#!/usr/bin/env bash

USERNAME="samba_user"
PASSWORD="test"
CONTAINER="websites"

# Function to run a command in the container and check its status
run_in_container() {
  nixos-container run "$CONTAINER" -- $1
  if [ $? -ne 0 ]; then
    echo "Failed: $1"
    exit 1
  fi
}

run_in_container "mkdir -p /tmp/samba"
run_in_container "chmod 777 /tmp/samba"
echo "folder for remote share created."

run_in_container "smbpasswd -a $USERNAME"
echo "password set."

run_in_container "smbd"
echo "smbd started."

run_in_container "nmbd"
echo "nmbd started."
